env: develop
host: 0.0.0.0:8080
tls:
  tlsMode: false
  crtFile: ssl/server.crt
  pemFile: ssl/server.pem
db:
  host: db
  username: root
  password: root
  schema: balance
  port: 3306
  debugMode: true
redis:
  host: "localhost"
  port: 6379
  password: ""
  key: "my-investment"
secret:
  tokenSymmetricKey: 12345678901234567890123456789012
  accessTokenDuration: 15m
